[tools]
chezmoi = "latest"
eza = "latest"
fzf = "latest"
github-cli = "latest"
rust = "latest"
usage = "latest"
zoxide = "latest"
just = "latest"
zellij = "latest"
awscli = { version = "latest", symlink_bins = "true" }
terraform = "latest"
node = "latest"
terragrunt = "latest"
postgres = "16"
atuin = "latest"
python = "latest"
minikube = "latest"
kubectl = "latest"
helm = "latest"
kustomize = "latest"
mkcert = "latest"
tilt = "latest"
k9s = "latest"
